# Generated by Django 5.2.14 on 2026-05-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('race_type', models.CharField(choices=[('chaos', 'Хаос'), ('imperium', 'Империум'), ('space_marine', 'Космо Десант'), ('xenos', 'Ксеносы')], default='xenos', max_length=50, verbose_name='Раса')),
                ('faction', models.CharField(help_text='Например: Blood Angels, Black Legion, Necrons', max_length=100, verbose_name='Фракция (Орден/Легион)')),
                ('miniatures_count', models.PositiveIntegerField(default=1, verbose_name='Кількість мініатюр в наборі')),
                ('set_type', models.CharField(max_length=100, verbose_name='Тип набору')),
                ('material', models.CharField(max_length=100, verbose_name='Матеріал')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image_main', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Главное фото')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
